name: Generate Signatures

on:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours
  workflow_dispatch:  # Allow manual triggering
  push:
    paths-ignore:
      - '**'  # Ignore all paths on push

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-signatures:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Git credentials
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.GH_PAT }}:x-oauth-basic@github.com" > ~/.git-credentials

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e git+https://${{ secrets.GH_PAT }}@github.com/mavroudisv/stampr_ai-collector.git#egg=stampr_ai_collector
          python -c "import sys; print(sys.path)"

      - name: Generate Signatures
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd operations
          PYTHONPATH=$PYTHONPATH:$(pwd)/.. python generate.py --timeout 600

      - name: Commit and Push Signatures
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add signatures/ signatures.json
          git commit -m "Update signatures [skip ci]"
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 