name: Generate Signatures

on:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours
  workflow_dispatch:  # Allow manual triggering
  push:
    paths-ignore:
      - '**'  # Ignore all paths on push

jobs:
  generate-signatures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Git credentials
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.GH_PAT }}:x-oauth-basic@github.com" > ~/.git-credentials

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r operations/requirements.txt

      - name: Generate Signatures
        run: |
          cd operations
          python generate.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages 